# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 321ad8e9ed959803e93e1eb8d8b651ac0ad188b8649b995a7c6afd7fd11e0aa185d042da4b19c1303279b161f105b658748f6cdffe4cbd0ce7d55d9980d95cdc

test:
  secret_key_base: ad2ced8e2e0a2a8532c77e76c8fc9babf0c658131c704844339a4171cd69667f6c319def18c878c93c744e9c3f4b07f7b8564e9ae2736996af9d2f598f43b51a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
